removed unsafe uses of /tmp/ with $$

diff --git a/src/shell/noroff b/src/shell/noroff
--- a/src/shell/noroff
+++ b/src/shell/noroff
@@ -37,7 +37,8 @@ base="`basename $1 | sed '/\./s/\.[^.]*$//'`"
 tagsfile="$base.nwt"
 (echo ".so $macrodir/tmac.w"
 if [ -r "$tagsfile" ]; then 
-   cp $tagsfile /tmp/tags.$$
+   tagstemp=$(mktemp) || { echo "$0: Cannot create temporary file" >&2; exit 1;  }
+   cp $tagsfile $tagstemp
    $AWK '{
 	     if      (sub(/^###TAG### /       , "")) tags[$1] = $2
 	     else if (sub(/^###BEGINCHUNKS###/, "")) printf ".de CLIST\n.CLISTBEGIN\n"
@@ -88,8 +89,8 @@ if [ -r "$tagsfile" ]; then
 	 #	print str3
 	 #	print convquote(str3)
 	 # }
-	 function tag(s) { if (s in tags) return tags[s]; else return "???" }' /tmp/tags.$$
-   rm -f /tmp/tags.$$
+	 function tag(s) { if (s in tags) return tags[s]; else return "???" }' $tagstemp
+   rm -f $tagstemp
  fi
  cat "$@") |
 ($ROFF $opts 2>$tagsfile)
diff --git a/src/shell/toroff b/src/shell/toroff
--- a/src/shell/toroff
+++ b/src/shell/toroff
@@ -9,7 +9,7 @@ for i do
            exit 1;;
     esac
 done
-awkfile="/tmp/noweb$$.awk"
+awkfile=$(mktemp) || { echo "$0: Cannot create temporary file" >&2; exit 1;  }
 trap 'rm -f $awkfile' 0 1 2 10 14 15
 cat > $awkfile << 'EOF'
 /^@begin docs 0$/ { if (delay) next }
